services:
  market-db:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    restart: always
    env_file:
      - .env    #change it on .env-example
    environment:
      - POSTGRES_DB=market
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data


  market-service:
    build: .
    expose:
      - "8080"
    depends_on:
      - market-db
    env_file:
      - .env
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://market-db:5432/market
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
    deploy:
      mode: replicated
      replicas: 2

  nginx:
    image: nginx:alpine
    restart: always
    environment:
      - NGINX_PORT=8080
    volumes:
      - ./nginx.conf:/etc/nginx/templates/nginx.conf.template
    ports:
       - "${APP_PORT:-8080}:8080"
    depends_on:
      - market-service

volumes:
  postgres_data: